server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3320/testDb
    username: user
    password: userPwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show_sql: true
      hbm2ddl:
        auto: update

  r2dbc:
    url: r2dbc:mysql://localhost:3320/testDb
    username: user
    password: userPwd