server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST_IP:localhost:3320}/${DB_NAME:testDb}
    username: ${DB_USERNAME:user}
    password: ${DB_PWD:userPwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show_sql: true
      hbm2ddl:
        auto: update

  r2dbc:
    url: r2dbc:mysql://${DB_HOST_IP:localhost:3320}/${DB_NAME:testDb}
    username: ${DB_USERNAME:user}
    password: ${DB_PWD:userPwd}